I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 38, in script call
    call rhythm_game_entry_label from _call_rhythm_game_entry_label
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 39, in script
    $ new_score = renpy.call_screen(_screen_name='rhythm_game', rhythm_game_displayable=rhythm_game_displayable)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 39, in <module>
    $ new_score = renpy.call_screen(_screen_name='rhythm_game', rhythm_game_displayable=rhythm_game_displayable)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 495, in event
    self.score += SCORE_GOOD
NameError: name 'SCORE_GOOD' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 38, in script call
    call rhythm_game_entry_label from _call_rhythm_game_entry_label
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 39, in script
    $ new_score = renpy.call_screen(_screen_name='rhythm_game', rhythm_game_displayable=rhythm_game_displayable)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 39, in <module>
    $ new_score = renpy.call_screen(_screen_name='rhythm_game', rhythm_game_displayable=rhythm_game_displayable)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\exports.py", line 3181, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\core.py", line 4258, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\screen.py", line 743, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\ew226\Desktop\CSE155\renpy-8.0.3-sdk\renpy\display\layout.py", line 1175, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "game/00-renpythm/rhythm_game_displayable.rpy", line 495, in event
    self.score += SCORE_GOOD
NameError: name 'SCORE_GOOD' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
